### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by mxsph** [thm-mni-ii/digital-classroom#55]
The design of the frontend is still very basic and should be adapted. Probably it is the best if we agree on a basic design philosophy and then apply it to everything.

## Components/areas that need adjustment

- [x] Adjust title (e.g. `digital classroom`)
- [x] Adjust favicon
- [x] Adjust conference list (possibly show on a separate page/popover)
- [x] Adjust design of dialogs
- [x] Add tooltips for conference enter/invite buttons
- [x] Remove priority as it can't be changed at the moment anyway? (@snicki13 what do you mean?)
- [x] Adjust the ticket design
- [x] Adjustment of the user list (Since for #19 an avatar should be displayed)
- [x] Style `logout.component`
- [x] 404 page
- [x] Replace the custom `date functions` with `date-fns` (see https://github.com/thm-mni-ii/digital-classroom/pull/73#discussion_r727402539).

**Comment by snicki13** [comment]
The priority is an absurd concept at this moment. Letting students choose the priority of a ticket leads to arbitrary priorities. Perhaps it may be reintroduced later to let instructors assign priorities, when there are multiple tickets in line.
